name: Auto Merge Labib Branch

on:
  push:
    branches:
      - Labibs_part

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge Labibs_part into main
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git checkout main
          git pull origin main

          git merge origin/Labibs_part --no-edit

          git push origin main
